aboveboard/games/routes.py
from flask import (
    flash, render_template,
    redirect, request, url_for, Blueprint)
from aboveboard import mongo
from aboveboard.games.utils import PER_PAGE, convert_to_pagination, avg_ratings
from aboveboard.games.forms import AddGameForm, SearchForm, EditGameForm
from aboveboard.models import Genre, Mechanic, Game
from flask_login import current_user, login_required
from flask_pymongo import ObjectId

games = Blueprint('games', __name__)


@games.route("/all-games", methods=["GET", "POST"])
def all_games():
    form = SearchForm()
    if form.validate_on_submit():
        query = form.query.data
        games = Game.get_searched_games(query)
    else:
        games = Game.get_all_games()
    games = list(games)
    # set ratings as a rounded average of the list of ints
    for game in games:
        game['rating'] = round(sum(game['rating'])/len(game['rating']))
    games = sorted(games, key=lambda i: i['title'])
    pagination, games_paginated = convert_to_pagination(
        games, PER_PAGE, "page", "per_page")
    return render_template("all-games.html",
                           games=games_paginated,
                           form=form,
                           pagination=pagination,
                           title='All Games')


@games.route("/my-games", methods=["GET", "POST"])
@login_required
def my_games():
    form = SearchForm()
    if form.validate_on_submit():
        query = form.query.data
        search_all_games = Game.get_searched_games(query)
        games = [game for game in search_all_games
                 if game['added_by'] == current_user.username]

    else:
        search_my_games = Game.get_my_games(current_user)
        games = list(search_my_games)
    for game in games:
        game['rating'] = round(sum(game['rating'])/len(game['rating']))
    games = sorted(games, key=lambda i: i['title'])
    pagination, games_paginated = convert_to_pagination(
        games, PER_PAGE, "page", "per_page")
    return render_template('my-games.html', title='My Games',
                           games=games_paginated, pagination=pagination,
                           form=form)


@games.route("/view-game/<gameid>", methods=["GET", "POST"])
def view_game(gameid):
    if request.method == 'POST':
        if current_user.is_authenticated:
            new_rating = request.form.get('rating')
            new_rating = [int(new_rating)]
            game = mongo.db.games.find_one({"_id": ObjectId(gameid)})
            new_rating = game['rating'] + new_rating
            mongo.db.games.update_one(
                {"_id": ObjectId(gameid)},
                {'$set': {'rating': new_rating}})
            flash('Game rated!', 'success')
            return redirect(url_for('games.all_games'))
        else:
            flash('You do not have permission to do that.', 'warning')
            return redirect(url_for('games.all_games'))
    ref = request.referrer
    try:
        game = Game.get_one_game(gameid)
        game_as_list = list(game)
        if len(game_as_list) == 0:
            flash('Game could not be found, or does not exist', 'warning')
            return redirect(url_for('games.all_games'))
        avg_rating, num_ratings = avg_ratings(game_as_list[0]['rating'])
        return render_template("view-game.html",
                               game=game_as_list,
                               ref=ref,
                               rating=avg_rating,
                               num_ratings=num_ratings,
                               title='Game Info')
    except Exception:
        flash('Game could not be found, or does not exist', 'warning')
        return redirect(url_for('games.all_games'))


@games.route("/add-game", methods=["GET", "POST"])
@login_required
def add_game():
    form = AddGameForm()
    placehold = 'https://via.placeholder.com/250x200?text=No+Box+Art+Provided'
    base_list = ['Choose an Option']
    list_of_genres = Genre.list_genres()
    list_of_mechanics = Mechanic.list_mechanics()
    form.genre.choices = base_list + list_of_genres
    form.mechanics.choices = base_list + list_of_mechanics
    if form.validate_on_submit():
        if form.image_link.data == '':
            form.image_link.data = placehold
        form_data = form.make_dict()
        form_data['added_by'] = current_user.username
        new_game = Game(**form_data)
        new_game.add_game(current_user)
        flash('Game Successfully Added!', 'success')
        return redirect(url_for('games.all_games'))
    return render_template("add-game.html", form=form, title="Add A Game")


@games.route("/delete-game/<gameid>")
@login_required
def delete_game(gameid):
    try:
        find_game = mongo.db.games.find_one({"_id": ObjectId(gameid)})
        game = Game(**find_game)
        users = [game.added_by, 'admin']
        if current_user.username in users:
            Game.delete_one_game(gameid)
            flash('Game has been deleted!', 'success')
            return redirect(url_for('games.all_games'))
        else:
            flash('You do not have permission to delete that game', 'warning')
            return redirect(url_for('games.all_games'))
    except Exception:
        flash('That game could not be found!', 'warning')
        return redirect(url_for('games.all_games'))


@games.route("/edit-game/<gameid>", methods=["GET", "POST"])
@login_required
def edit_game(gameid):
    game = mongo.db.games.find_one({"_id": ObjectId(gameid)})
    users = [game['added_by'], 'admin']
    if current_user.username not in users:
        flash('You do not have permission to do that.', 'warning')
        return redirect(url_for('games.all_games'))
    form = EditGameForm()
    if form.validate_on_submit():
        changes = form.collect_changes()
        mongo.db.games.update_one({'_id': ObjectId(gameid)},
                                  {'$set': changes})
        flash('Game info edited!', 'success')
        return redirect(url_for('games.all_games'))

    elif request.method == 'GET':
        form.set_form_data(game)

    return render_template('edit-game.html', form=form)

aboveboard/main/routes.py
from flask import render_template, Blueprint
from aboveboard import mongo

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    # sort through db in reverse order and get the 3 most recent additions
    games = mongo.db.games.find().hint([('$natural', -1)]).limit(3)
    games = list(games)
    # set ratings as a rounded average of the list of ints
    for game in games:
        game['rating'] = round(sum(game['rating'])/len(game['rating']))
    return render_template("home.html", games=games)

aboveboard/users/routes.py
from flask import (
    flash, render_template,
    redirect, request, url_for, Blueprint)
from aboveboard import mongo, bcrypt
from aboveboard.models import User
from aboveboard.users.utils import send_password_reset
from aboveboard.users.forms import (RegistrationForm, LoginForm,
                                    UpdateAccountForm, RequestResetForm,
                                    ResetPasswordForm, AdminForm)
from flask_login import login_user, current_user, logout_user, login_required

users = Blueprint('users', __name__)


@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        register = form.make_dict()
        new_user = User(**register)
        new_user.add_user()
        flash(f'Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        find_user = mongo.db.users.find_one({'email': form.email.data})
        check_password = False
        if find_user:
            check_password = bcrypt.check_password_hash(
                find_user['password'], form.password.data)
        if find_user and check_password:
            user = User(**find_user)
            login_user(user, remember=form.remember.data)
            flash('You have been logged in!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(
                url_for('main.home'))
        else:
            flash('Incorrect email or password, please try again.', 'warning')

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
def logout():
    if current_user.is_authenticated:
        logout_user()
        flash('You have been logged out!', 'success')
    else:
        flash('You are not currently logged in.', 'info')
    return redirect(url_for('main.home'))


@users.route("/profile", methods=["GET", "POST"])
@login_required
def profile():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        mongo.db.users.update_one({'username': current_user.username},
                                  {'$set': {
                                      'fname': form.fname.data,
                                      'lname': form.lname.data,
                                      'email': form.email.data
                                  }
        })
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        user = mongo.db.users.find_one({'username': current_user.username})
        form.fname.data = user['fname']
        form.lname.data = user['lname']
        form.email.data = user['email']

    return render_template('profile.html', title='Profile', form=form)


@users.route("/reset_password", methods=["GET", "POST"])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        find_user = mongo.db.users.find_one({'email': form.email.data})
        user = User(**find_user)
        send_password_reset(user)
        flash(
            'An email with instructions to reset your password has been sent.',
            'success')
        return redirect(url_for('users.login'))
    return render_template('request-reset.html',
                           title='Request Password Reset', form=form)


@users.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.check_token(token)
    if not user:
        flash('Unable to proceed. Please try again.', 'warning')
        return redirect(url_for('users.request_reset'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        new_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        mongo.db.users.update({'username': user['username']},
                              {'$set': {
                                  'password': new_password
                              }
        })
        flash('Your password has been updated!', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset-token.html', title='Reset Password',
                           form=form)


@users.route("/admin", methods=["GET", "POST"])
@login_required
def admin():
    if current_user.username != 'admin':
        flash('You do not have permission to do that', 'warning')
        return redirect(url_for('main.home'))
    form = AdminForm()
    if form.validate_on_submit():
        if form.genre.data:
            mongo.db.genres.insert_one({'genre': form.genre.data})
        if form.mechanics.data:
            mongo.db.mechanics.insert_one({'mechanics': form.mechanics.data})
        flash('Category updated', 'success')
        return redirect(url_for('users.admin'))
    return render_template('admin.html', form=form, title='Admin')

aboveboard/templates/all-games.html
{% extends 'base.html' %}
{% block content%}
<h1 class="text-center">Above Board</h1>
<div class="row">
    <div class="col s12 m10 offset-m1">
        <div class="row">
            <div class="col s12 m6">
                {% if current_user.is_authenticated %}
                <h4>
                    <a href="{{ url_for('games.add_game') }}" class="add-game">
                        <i class="fas fa-plus-circle"></i> Add a Game</a>
                </h4>
                {% endif %}
            </div>
            <div class="col s12 m6">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <div class="input-field col s12 l6">
                        <i class="prefix fas fa-search"></i>
                        {{ form.query.label }}
                        {% if form.query.errors %}
                            {{ form.query(class="invalid") }}
                            {% for error in form.query.errors %}
                                <span class="helper-text" data-error="{{ error }}"></span>
                            {% endfor %}
                        {% else %}
                            {{ form.query(class="validate") }}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 l6 text-center submit-btn">
                        {{ form.submit(class="btn waves-effect waves-light")}}
                        <a href="{{ url_for('games.all_games') }}" class="btn red waves-effect waves-light">Reset</a>
                    </div>
                </form>
            </div>
        </div>
        {% if games|length > 0 %}
        <div class="card-panel outer-panel">
            <div class="row">
                {% for game in games %}
                    <div class="col s12 m6 l3">
                        <a href="{{ url_for('games.view_game', gameid=game._id) }}" class="game-link">
                            <div class="card-panel game-panel">
                                <div class="row">
                                    <div class="col s12">
                                        <p class="game-title text-center">{{ game.title }}</p>
                                    </div>
                                    <div class="col s12">
                                        <img class="box-art" src="{{ game.image_link }}" alt="{{ game.title }} box art">
                                    </div>
                                    <div class="col s6 game-info"><b>Player Count:</b> {{ game.player_count }}</div>
                                    <div class="col s6 game-info"><b>Mechanics:</b> {{ game.mechanics.title() }}</div>
                                    <div class="col s6 game-info"><b>Genre:</b> {{ game.genre.title() }}</div>
                                    <div class="col s6 game-info"><b>Rating:</b> {{ game.rating }}/5</div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        <!-- Pagination info and controls -->
        <div class="row paginate-row">
            <div class="col s12 m6">
                {{ pagination.info }}
            </div>
            <div class="col s12 m6">
                {{ pagination.links }}
            </div>
        </div>
    </div>
    {% else %}
        <h4 class="center-align">No Results Found</h4>
    {% endif %}
</div>
{% endblock %}

aboveboard/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Favicon -->
    <link rel="icon" href="{{ url_for('static', filename='favicons/favicon.ico') }}">

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
        integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Materialize CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css"
        type="text/css">

    <!-- style.css -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    {% if title %}
        <title>Above Board | {{ title }}</title>
    {% else %}
        <title>Above Board</title>
    {% endif %}

</head>

<body>
    <!-- Return to top button -->
    <button id="toTopBtn" aria-label="Return to top button"><i class="fas fa-chevron-up"></i></button>
    <header>
        <nav>
            <div class="nav-wrapper yellow accent-2">
                <a href="{{ url_for('main.home') }}" class="navbar-logo">
                    <img src="{{ url_for('static', filename='images/brand-logo.png')}}" alt="Brand Logo for Above Board"
                        height="60" width="56">
                    <h5 class="black-text">Above Board</h5>
                </a>
                <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i
                        class="fas fa-bars black-text"></i></a></a>
                <ul class="right hide-on-med-and-down nav-list">
                    <li><a href="{{ url_for('main.home') }}">Home</a></li>
                    <li><a href="{{ url_for('games.all_games') }}">All Games</a></li>
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('games.my_games') }}">My Games</a></li>
                        <li><a href="{{ url_for('users.profile') }}">My Profile</a></li>
                        <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
                    {% else %}
                        <li><a href="{{ url_for('users.login') }}">Login</a></li>
                        <li><a href="{{ url_for('users.register') }}">Register</a></li>
                    {% endif %}
                    {% if current_user.username == 'admin' %}
                        <li><a href="{{ url_for('users.admin') }}">Admin</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>


        <ul class="sidenav right" id="mobile-demo">
            <li><a href="{{ url_for('main.home') }}">Home</a></li>
            <li><a href="{{ url_for('games.all_games') }}">All Games</a></li>
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('games.my_games') }}">My Games</a></li>
                <li><a href="{{ url_for('users.profile') }}">My Profile</a></li>
                <li><a href="{{ url_for('users.logout') }}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for('users.login') }}">Login</a></li>
                <li><a href="{{ url_for('users.register') }}">Register</a></li>
            {% endif %}
            {% if current_user.username == 'admin' %}
                <li><a href="{{ url_for('users.admin') }}">Admin</a></li>
            {% endif %}
        </ul>
    </header>
    <main>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                <div id="flashes-row" class="row">
                    {% for category, message in messages %}
                        <div class="col s12 m8 offset-m2">
                            <div class="text-center card-panel {{category}}">{{ message }} <i id="close-flashes"
                                    class="fas fa-window-close"></i></div>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
        {% endwith %}
        {% block content %}
        {% endblock %}
    </main>

    <footer class="grey darken-1">
        <div class="row">
            <div class="col s12 m6 copyright-div">
                <span class="white-text">© Aboveboard 2021</span>
            </div>
            <div class="col s12 m6 social-links-div">
                <div class="white-text">
                    <a href="https://twitter.com/" rel="noopener noreferrer" target="_blank">
                        <i class="fab fa-twitter-square social-links hvr-fade" aria-hidden="true"></i>
                        <span class="sr-only">Twitter</span>
                    </a>
                    <a href="https://github.com/kevinoc554/above-board" rel="noopener noreferrer" target="_blank">
                        <i class="fab fa-github social-links hvr-fade" aria-hidden="true"></i>
                        <span class="sr-only">Github</span>
                    </a>
                    <a href="https://www.instagram.com/" rel="noopener noreferrer" target="_blank">
                        <i class="fab fa-instagram social-links hvr-fade" aria-hidden="true"></i>
                        <span class="sr-only">Instagram</span>
                    </a>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

    <!-- Materialize JS CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <!-- script.js -->
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>

</body>

</html>

aboveboard/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="section grey hero-image">
    <div class="row">
        <div class="col s10 push-s1 m6 offset-m6 l4 offset-l8">
            <div class="card hero-card">
                <div class="card-content">
                    <span class="card-title text-center">Welcome to Above Board!</span>
                    <p class="hero-card-text">Above Board is a place for board gamers to catalogue and
                        rate their collections, see details of games added by others, and find something new to play!
                    </p>
                    <p class="hero-card-text">Click below to get started!</p>
                </div>
                <div class="card-action text-center">
                    {% if current_user.is_authenticated %}
                        <a href="{{ url_for('games.my_games') }}" class="btn hero-btn">Go to My Games!</a>
                    {% else %}
                        <a href="{{ url_for('users.register') }}" class="btn hero-btn">Sign Up Now!</a>
                        <small class="small-text login-link italics">Already Have An Account? <a
                                href="{{ url_for('users.login') }}">Login!</a></small>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="card-panel outer-panel recently-added-panel">
    <div class="row">
        <div class="col s12">
            <h4>Recently Added:</h4>
        </div>
        {% for game in games %}
            <div class="col s12 m6 l3">
                <a href="{{ url_for('games.view_game', gameid=game._id) }}" class="game-link">
                    <div class="card-panel game-panel">
                        <div class="row">
                            <div class="col s12">
                                <p class="game-title text-center">{{ game.title }}</p>
                            </div>
                            <div class="col s12">
                                <img class="box-art" src="{{ game.image_link }}" alt="{{ game.title }} box art">
                            </div>
                            <div class="col s6 game-info"><b>Player Count:</b> {{ game.player_count }}</div>
                            <div class="col s6 game-info"><b>Mechanics:</b> {{ game.mechanics.title() }}</div>
                            <div class="col s6 game-info"><b>Genre:</b> {{ game.genre.title() }}</div>
                            <div class="col s6 game-info"><b>Rating:</b> {{ game.rating }}/5</div>
                        </div>
                    </div>
                </a>
            </div>
        {% endfor %}
        <div class="col s12 m6 l3">
            <div class="card-panel game-panel">
                <h4 class="card-title">Actions:</h4>
                <hr class="action-hr">
                <div class="row">
                    {% if current_user.is_authenticated %}
                        <div class="col s12">
                            <a href="{{ url_for('games.add_game') }}" class="utility-links">
                                <p>
                                    <i class="fas fa-plus-circle"></i> Add a Game
                                </p>
                            </a>
                        </div>
                        <div class="col s12">
                            <a href="{{ url_for('games.my_games') }}" class="utility-links">
                                <p>
                                    <i class="fas fa-dice"></i> See My Games
                                </p>
                            </a>
                        </div>
                    {% else %}
                        <div class="col s12">
                            <a href="{{ url_for('users.register') }}" class="utility-links">
                                <p>
                                    <i class="fas fa-user"></i> Sign up!
                                </p>
                            </a>
                        </div>
                        <div class="col s12">
                            <a href="{{ url_for('games.all_games') }}" class="utility-links">
                                <p>
                                    <i class="fas fa-dice"></i> See All Games
                                </p>
                            </a>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

aboveboard/templates/my-games.html
{% extends 'base.html' %}
{% block content%}
<h1 class="text-center">Above Board</h1>
<div class="row">
    <div class="col s12 m10 offset-m1">
        <div class="row">
            <div class="col s12 m6">
                <h4>
                    <a href="{{ url_for('games.add_game') }}" class="add-game">
                        <i class="fas fa-plus-circle"></i> Add a Game</a>
                </h4>
            </div>
            <div class="col s12 m6">
                <form method="POST">
                    {{ form.hidden_tag() }}
                    <div class="input-field col s12 l6">
                        <i class="prefix fas fa-search"></i>
                        {{ form.query.label }}
                        {% if form.query.errors %}
                            {{ form.query(class="invalid") }}
                            {% for error in form.query.errors %}
                                <span class="helper-text" data-error="{{ error }}"></span>
                            {% endfor %}
                        {% else %}
                            {{ form.query(class="validate") }}
                        {% endif %}
                    </div>
                    <div class="input-field col s12 l6 text-center submit-btn">
                        {{ form.submit(class="btn waves-effect waves-light")}}
                        <a href="{{ url_for('games.my_games') }}" class="btn red waves-effect waves-light">Reset</a>
                    </div>
                </form>
            </div>
        </div>
        {% if games|length > 0 %}
            <div class="card-panel outer-panel">
                <div class="row">
                    {% for game in games %}
                        <div class="col s12 m6 l3">
                            <a href="{{ url_for('games.view_game', gameid=game._id) }}" class="game-link">
                                <div class="card-panel game-panel">
                                    <div class="row">
                                        <div class="col s12">
                                            <p class="game-title text-center">{{ game.title }}</p>
                                        </div>
                                        <div class="col s12">
                                            <img class="box-art" src="{{ game.image_link }}" alt="{{ game.title }} box art">
                                        </div>
                                        <div class="col s6 game-info"><b>Player Count:</b> {{ game.player_count }}</div>
                                        <div class="col s6 game-info"><b>Mechanics:</b> {{ game.mechanics.title() }}</div>
                                        <div class="col s6 game-info"><b>Genre:</b> {{ game.genre.title() }}</div>
                                        <div class="col s6 game-info"><b>Rating:</b> {{ game.rating }}/5</div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <!-- Pagination info and controls -->
            <div class="row paginate-row">
                <div class="col s12 m6">
                    {{ pagination.info }}
                </div>
                <div class="col s12 m6">
                    {{ pagination.links }}
                </div>
            </div>
        </div>
    {% else %}
        <h4 class="center-align">No Results Found</h4>
    {% endif %}
</div>
{% endblock %}

aboveboard/templates/request-reset.html
{% extends 'base.html' %}
{% block content%}
<div class="row">
    <div class="col s12 m10 offset-m1">
        <div class="card-panel outer-panel">
            <div class="row">
                <div class="col s12">
                    <h1 class="text-center"><span>Above</span> <span>Board</span></h1>
                    <p class="text-center bold sub-heading">Request Password Reset</p>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m10 offset-m1">
                    <div class="card-panel">
                        <form method="POST">
                            {{ form.hidden_tag() }}
                            <fieldset>
                                <legend>Reset Password</legend>
                                <div class="input-field col s12">
                                    <i class="prefix fas fa-envelope"></i>
                                    {{ form.email.label }}
                                    {% if form.email.errors %}
                                        {{ form.email(class="invalid") }}
                                        {% for error in form.email.errors %}
                                            <span class="helper-text" data-error="{{ error }}"></span>
                                        {% endfor %}
                                    {% else %}
                                        {{ form.email(class="validate") }}
                                    {% endif %}
                                </div>
                            </fieldset>
                            <div class="input-field text-center submit-btn">
                                {{ form.submit(class="btn waves-effect waves-light")}}
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}